############# English navigation ##############

# main menu


# footer menu
[[footer]]
name = "About"
url = "https://sudofishlabs.github.io/"
weight = 1

[[footer]]
name = "Contact Us"
url = "mailto:asd@example.com"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 3
